name: 'healthcare_mesh'
version: '1.0.0'
config-version: 2

# This MUST match the profile name in your ~/.dbt/profiles.yml
profile: 'healthcare_mesh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  healthcare_mesh:
    # This applies to all models in the project
    +materialized: table