name: dbt_ci

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt-trino
        run: pip install dbt-trino

      - name: dbt Parse & Compile
        run: |
          cd dbt_project
          dbt parse # Validates model definitions
          dbt compile # Checks if SQL is valid without running it