name: dbt_ci

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt-trino
        run: pip install dbt-trino

      - name: Configure dbt profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          healthcare_mesh:
            target: dev
            outputs:
              dev:
                type: trino
                method: none
                user: admin
                host: localhost
                port: 8080
                catalog: iceberg
                schema: landing
                threads: 4
                http_scheme: http
          EOF

      - name: dbt Parse & Compile
        run: |
          cd dbt_project
          dbt parse # Validates model definitions
          dbt compile # Checks if SQL is valid without running it